# Generated by Django 2.2.4 on 2019-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('nit_empresa', models.CharField(max_length=50)),
                ('tel_empresa', models.CharField(max_length=10)),
                ('direc_empresa', models.CharField(max_length=50)),
            ],
        ),
    ]
